//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupEvaluation
    {
        public int GroupId { get; set; }
        public int EvaluationId { get; set; }
        public int ObtainedMarks { get; set; }
        public System.DateTime EvaluationDate { get; set; }
    
        public virtual Evaluation Evaluation { get; set; }
        public virtual Group Group { get; set; }
    }
}
