//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupStudent
    {
        public int GroupId { get; set; }
        public int StudentId { get; set; }
        public int Status { get; set; }
        public System.DateTime AssignmentDate { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Student Student { get; set; }
    }
}
