//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAdvisor
    {
        public int AdvisorId { get; set; }
        public int ProjectId { get; set; }
        public int AdvisorRole { get; set; }
        public System.DateTime AssignmentDate { get; set; }
    
        public virtual Advisor Advisor { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Project Project { get; set; }
    }
}
